import {
  receitaFixaSchema,
  saidaFixaSchema,
  compraCartaoSchema,
  entradaExtraSchema,
  cenarioSimuladoSchema,
  lancamentoDiarioSchema,
  aporteCdbSchema,
} from "@cf/shared";
import { asValidavel, type RecursoConfig } from "../../lib/campos";

export const RECURSOS: Record<string, RecursoConfig> = {
  "receitas-fixas": {
    endpoint: "/api/v1/receitas-fixas",
    chave: "receitas-fixas",
    titulo: "Receitas Fixas",
    descricao: "Entradas recorrentes garantidas (ex.: salário).",
    schema: asValidavel(receitaFixaSchema),
    tituloCampo: "descricao",
    campos: [
      { nome: "descricao", label: "Descrição", tipo: "texto" },
      { nome: "valor", label: "Valor", tipo: "moeda" },
      { nome: "diaRecebimento", label: "Dia do mês", tipo: "numero", min: 1, max: 31 },
      { nome: "ativa", label: "Ativa", tipo: "checkbox", padrao: true },
    ],
  },
  "saidas-fixas": {
    endpoint: "/api/v1/saidas-fixas",
    chave: "saidas-fixas",
    titulo: "Saídas Fixas",
    descricao: "Contas recorrentes (aluguel, assinaturas…).",
    schema: asValidavel(saidaFixaSchema),
    tituloCampo: "descricao",
    campos: [
      { nome: "descricao", label: "Descrição", tipo: "texto" },
      { nome: "valor", label: "Valor", tipo: "moeda" },
      { nome: "diaVencimento", label: "Dia do vencimento", tipo: "numero", min: 1, max: 31 },
      { nome: "categoria", label: "Categoria", tipo: "texto" },
      { nome: "ativa", label: "Ativa", tipo: "checkbox", padrao: true },
    ],
  },
  "compras-cartao": {
    endpoint: "/api/v1/compras-cartao",
    chave: "compras-cartao",
    titulo: "Cartão de Crédito",
    descricao: "Compras parceladas lançadas na fatura.",
    schema: asValidavel(compraCartaoSchema),
    tituloCampo: "descricao",
    campos: [
      { nome: "descricao", label: "Descrição", tipo: "texto" },
      { nome: "valorTotal", label: "Valor total", tipo: "moeda" },
      { nome: "numParcelas", label: "Nº de parcelas", tipo: "numero", min: 1 },
      { nome: "dataPrimeiraParcela", label: "1ª parcela", tipo: "data" },
    ],
  },
  "entradas-extras": {
    endpoint: "/api/v1/entradas-extras",
    chave: "entradas-extras",
    titulo: "Entradas Extras",
    descricao: "Dinheiro extra confirmado, não recorrente.",
    schema: asValidavel(entradaExtraSchema),
    tituloCampo: "descricao",
    campos: [
      { nome: "descricao", label: "Descrição", tipo: "texto" },
      { nome: "valor", label: "Valor", tipo: "moeda" },
      { nome: "data", label: "Data", tipo: "data" },
      {
        nome: "confirmada",
        label: "Confirmada",
        tipo: "checkbox",
        padrao: false,
        ajuda: "Só marque quando o dinheiro é garantido (trabalho entregue, contrato assinado). Nunca “acho que vou receber”.",
      },
    ],
  },
  "lancamentos-diarios": {
    endpoint: "/api/v1/lancamentos-diarios",
    chave: "lancamentos-diarios",
    titulo: "Lançamentos Diários",
    descricao: "Gastos variáveis do dia a dia.",
    schema: asValidavel(lancamentoDiarioSchema),
    tituloCampo: "descricao",
    campos: [
      { nome: "descricao", label: "Descrição", tipo: "texto" },
      { nome: "valorGasto", label: "Valor gasto", tipo: "moeda" },
      { nome: "data", label: "Data", tipo: "data" },
      { nome: "categoria", label: "Categoria", tipo: "texto", ajuda: "Deve bater com uma categoria de orçamento." },
    ],
  },
  "aportes-cdb": {
    endpoint: "/api/v1/aportes-cdb",
    chave: "aportes-cdb",
    titulo: "Aportes CDB",
    descricao: "Aportes reduzem a conta; resgates a aumentam.",
    schema: asValidavel(aporteCdbSchema),
    tituloCampo: "tipo",
    campos: [
      {
        nome: "tipo",
        label: "Tipo",
        tipo: "select",
        padrao: "aporte",
        opcoes: [
          { valor: "aporte", label: "Aporte" },
          { valor: "resgate", label: "Resgate" },
        ],
      },
      { nome: "valor", label: "Valor", tipo: "moeda" },
      { nome: "data", label: "Data", tipo: "data" },
      { nome: "observacao", label: "Observação", tipo: "texto" },
    ],
  },
  "cenarios-simulados": {
    endpoint: "/api/v1/cenarios-simulados",
    chave: "cenarios-simulados",
    titulo: "Simulador (E se…?)",
    descricao: "Cenários hipotéticos — só afetam a projeção quando marcados como incluídos.",
    schema: asValidavel(cenarioSimuladoSchema),
    tituloCampo: "descricao",
    campos: [
      { nome: "descricao", label: "Descrição", tipo: "texto" },
      {
        nome: "tipo",
        label: "Tipo",
        tipo: "select",
        padrao: "entrada",
        opcoes: [
          { valor: "entrada", label: "Entrada" },
          { valor: "saida", label: "Saída" },
        ],
      },
      { nome: "valor", label: "Valor", tipo: "moeda" },
      { nome: "data", label: "Data", tipo: "data" },
      { nome: "incluir", label: "Incluir na projeção", tipo: "checkbox", padrao: false },
    ],
  },
};
